### ISSUE TITLE
Calculate quantiles should accept bin_count

### ISSUE THREAD

**Issue by michaelpkuhn** [Code-For-Chicago/greater-chicago-food-despository#62]
FE wants 5 quantile bins (currently set to 4). In implementing this feature, `calculate_quantile_bins` should accept `bin_count` variable like natural breaks function.

`q` (the bounds of the bins) would increment by `1/bin_count` from 0 to 1. Round to two digits to avoid floating point issues.

**Comment by brickman1444** [comment]
@michaelpkuhn do they also want 5 natural breaks bins?
